/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDialog: typeof import('./src/components/App/AppDialog.vue')['default']
    AppDrawer: typeof import('./src/components/App/AppDrawer.vue')['default']
    AppSvgIcon: typeof import('./src/components/App/AppSvgIcon.vue')['default']
    BarChart: typeof import('./src/components/BarChart.vue')['default']
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    PieChart: typeof import('./src/components/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tag: typeof import('primevue/tag')['default']
    UsersDataTable: typeof import('./src/components/Useres/UsersDataTable.vue')['default']
    UserTable: typeof import('./src/components/Useres/UserTable.vue')['default']
  }
}
